Repository IP-I-s-Protocol/DDang, pull requests merged in 2024-04, with the labels that each got.

#13 Feat/cicd1 : workflow 추가, DB 이중화 코드 구현
  .github/workflows/build.yml
  .gitignore
  src/main/java/com/ip/ddangddangddang/global/config/DataSourceConfig.java
  src/main/java/com/ip/ddangddangddang/global/config/DynamicRoutingDataSource.java
  src/main/java/com/ip/ddangddangddang/global/constant/AppConstant.java
  src/main/resources/application.properties
Labels: enhancement

#14 Feat/auction : 메인화면 옥션 글 조회 기능 구현
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: enhancement

#17 Feat/bid : 입찰 기능 구현
  src/main/java/com/ip/ddangddangddang/domain/bid/controller/BidController.java
  src/main/java/com/ip/ddangddangddang/domain/bid/dto/request/BidRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/bid/entity/Bid.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidRepository.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
Labels: enhancement

#20 Feat/global : ExceptionHandler 추가 및 패키지 이동
  .gitignore
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/exception/AuctionErrorCode.java
  src/main/java/com/ip/ddangddangddang/domain/auction/exception/CustomAuctionException.java
  src/main/java/com/ip/ddangddangddang/domain/bid/entity/Bid.java
  src/main/java/com/ip/ddangddangddang/domain/bid/exception/BidErrorCode.java
  src/main/java/com/ip/ddangddangddang/domain/bid/exception/CustomBidException.java
  src/main/java/com/ip/ddangddangddang/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/ip/ddangddangddang/domain/comment/exception/CustomCommentException.java
  src/main/java/com/ip/ddangddangddang/domain/common/dto/CommonResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/common/dto/ExceptionDto.java
  src/main/java/com/ip/ddangddangddang/domain/common/timestamp/Timestamp.java
  src/main/java/com/ip/ddangddangddang/domain/result/exception/CustomResultException.java
  src/main/java/com/ip/ddangddangddang/domain/result/exception/ResultErrorCode.java
  src/main/java/com/ip/ddangddangddang/domain/user/entity/User.java
  src/main/java/com/ip/ddangddangddang/domain/user/exception/CustomUserException.java
  src/main/java/com/ip/ddangddangddang/domain/user/exception/UserErrorCode.java
  src/main/java/com/ip/ddangddangddang/global/exception/ErrorCode.java
  src/main/java/com/ip/ddangddangddang/global/exception/ErrorResponse.java
  src/main/java/com/ip/ddangddangddang/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/CustomAuctionException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/CustomBidException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/CustomCommentException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/CustomResultException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/CustomTownException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/CustomUserException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/LoginFailException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/PasswordNotEqualsException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/TimeOutLockException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/UserNotFoundException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/UsernameAlreadyExistException.java
Labels: enhancement, refactor

#21 Feat/auction : repository 합침, model 삭제
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/model/AuctionModel.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: refactor

#22 Feat/global : healthCheck 메서드 구현
  src/main/java/com/ip/ddangddangddang/domain/common/controller/MainController.java
  src/main/java/com/ip/ddangddangddang/global/config/WebSecurityConfig.java
Labels: enhancement

#23 Feat/file : file 도메인 분리
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/request/AuctionRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/File.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/FileService.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/S3Service.java
  src/main/java/com/ip/ddangddangddang/domain/file/controller/FileController.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/request/ImageRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/entity/File.java
  src/main/java/com/ip/ddangddangddang/domain/file/repository/FileRepository.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileService.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/S3Service.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/EmptyImageException.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/NotValidBucketException.java
  src/main/resources/templates/login.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/signup.html
Labels: bug, enhancement

#28 Feat/file : file 컨벤션 맞추어 변경
  src/main/java/com/ip/ddangddangddang/domain/file/controller/FileController.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/request/FileCreateRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/response/FileCreateResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/response/FileReadResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/repository/FileRepository.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileService.java
Labels: enhancement

#29 Feat/town : 사용하지 않는 파일 삭제, repository 합침, user에서 사용할 메소드 구현
  src/main/java/com/ip/ddangddangddang/domain/town/dto/request/TownRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/town/dto/response/TownResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/town/entity/StringListConverter.java
  src/main/java/com/ip/ddangddangddang/domain/town/entity/Town.java
  src/main/java/com/ip/ddangddangddang/domain/town/model/TownModel.java
  src/main/java/com/ip/ddangddangddang/domain/town/repository/TownJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/town/repository/TownRepository.java
  src/main/java/com/ip/ddangddangddang/domain/town/repository/TownRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/town/service/TownService.java
  src/main/java/com/ip/ddangddangddang/domain/town/townList/TownListJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/town/townList/TownListRepository.java
  src/main/java/com/ip/ddangddangddang/domain/user/service/UserService.java
Labels: enhancement, refactor

#30 Feat/user : 위치수정 기능 구현
  src/main/java/com/ip/ddangddangddang/domain/user/controller/UserController.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserLocationRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserSignupRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/entity/User.java
  src/main/java/com/ip/ddangddangddang/domain/user/model/UserModel.java
  src/main/java/com/ip/ddangddangddang/domain/user/repository/UserJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/user/repository/UserRepository.java
  src/main/java/com/ip/ddangddangddang/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/user/service/UserService.java
  src/main/java/com/ip/ddangddangddang/global/config/WebSecurityConfig.java
  src/main/java/com/ip/ddangddangddang/global/security/JwtAuthenticationFilter.java
Labels: enhancement, refactor

#31 Feat/town : 메소드명 변경
  src/main/java/com/ip/ddangddangddang/domain/town/service/TownService.java
Labels: refactor

#32 Feat/cicd1 : redis distributedLock 추가 및 타이틀 키워드 검색 기능 구현
  build.gradle
  src/main/java/com/ip/ddangddangddang/DdangddangddangApplication.java
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/request/AuctionRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/global/aop/DistributedLock.java
  src/main/java/com/ip/ddangddangddang/global/aop/RedisLockAspect.java
  src/main/java/com/ip/ddangddangddang/global/config/JpaConfig.java
  src/main/java/com/ip/ddangddangddang/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/LockNotAcquiredException.java
Labels: enhancement, refactor

#33 Feat/front : 카카오맵 api에서 백엔드로 주는 정보 수정
  src/main/java/com/ip/ddangddangddang/domain/common/controller/MainController.java
  src/main/java/com/ip/ddangddangddang/global/config/WebSecurityConfig.java
  src/main/resources/templates/profile.html
  src/main/resources/templates/signup.html
Labels: enhancement

#34 Feat/comment : 댓글 작성 및 조회 구현
  src/main/java/com/ip/ddangddangddang/domain/comment/controller/CommentController.java
  src/main/java/com/ip/ddangddangddang/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/comment/dto/request/CommentRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/comment/dto/response/CommentReadResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/comment/entity/Comment.java
  src/main/java/com/ip/ddangddangddang/domain/comment/model/CommentModel.java
  src/main/java/com/ip/ddangddangddang/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/comment/repository/CommentRepository.java
  src/main/java/com/ip/ddangddangddang/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/comment/service/CommentService.java
Labels: enhancement, refactor

#35 Feat/bid : 본인 글에 입찰 못하게 변경
  src/main/java/com/ip/ddangddangddang/domain/bid/controller/BidController.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
Labels: refactor

#36 Feat/auction : 검색 쿼리 예외처리 추가 및 값 수정
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepositoryImpl.java
Labels: refactor

#39 Feat/file : 코드 리뷰 반영, auction 과의 직접매핑 설정
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/domain/bid/controller/BidController.java
  src/main/java/com/ip/ddangddangddang/domain/comment/controller/CommentController.java
  src/main/java/com/ip/ddangddangddang/domain/common/dto/CommonResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/controller/FileController.java
  src/main/java/com/ip/ddangddangddang/domain/file/entity/File.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileService.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileUploadService.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/S3Service.java
  src/main/java/com/ip/ddangddangddang/domain/user/controller/UserController.java
  src/main/java/com/ip/ddangddangddang/global/security/UserDetailsImpl.java
Labels: enhancement

#40 Feat/global : redis config 추가 및 customLock 적용
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
  src/main/java/com/ip/ddangddangddang/global/config/RedisConfig.java
Labels: enhancement

#42 Feat/auction : auction 만료기한 종료시 redis에서 호출
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/domain/file/entity/File.java
  src/main/java/com/ip/ddangddangddang/global/config/RedisConfig.java
  src/main/java/com/ip/ddangddangddang/global/redis/RedisKeyExpiredListener.java
Labels: enhancement

#44 Feat/Auction : EventLisetner로 의존성 처리
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/request/AuctionKeyNotificationRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/handler/AuctionEventHandler.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidRepository.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/global/redis/RedisKeyExpiredListener.java
Labels: enhancement

#45 Feat/front : js 파일 분리
  src/main/resources/static/js/basic.js
  src/main/resources/templates/auction.html
  src/main/resources/templates/index.html
Labels: enhancement

#47 Feat/result : Auction에 입찰자가 없을경우, 예외 처리
  src/main/java/com/ip/ddangddangddang/domain/comment/service/CommentService.java
  src/main/java/com/ip/ddangddangddang/domain/result/dto/request/ResultRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/result/dto/response/ResultResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/result/entity/Result.java
  src/main/java/com/ip/ddangddangddang/domain/result/repository/ResultJpaRepository.java
  src/main/java/com/ip/ddangddangddang/domain/result/repository/ResultRepository.java
  src/main/java/com/ip/ddangddangddang/domain/result/repository/ResultRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/result/service/ResultService.java
Labels: enhancement

#48 Feat/file : file 삭제 불가능 에러 해결
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/domain/file/controller/FileController.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/response/FileReadResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileService.java
Labels: enhancement

#49 Feat/auction : 판매자가 올린 게시글 조회, 본인이 최고 입찰가를 제시한 게시글 조회 API 구현
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionListResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: enhancement, refactor

#50 Feat/user : 로그인 실패 시 에러메세지 수정 및 서비스 메서드 수정
  src/main/java/com/ip/ddangddangddang/domain/user/service/UserService.java
  src/main/java/com/ip/ddangddangddang/global/exception/custom/UserEmailAlreadyExistException.java
  src/main/java/com/ip/ddangddangddang/global/security/JwtAuthenticationFilter.java
Labels: enhancement, refactor

#51 Feat/auction : 메인화면 조회 시 페이징 구현
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: refactor

#52 Feat/bid : 개발용 임시 JWT 토큰 및 ON_SALE만 입찰 가능
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
  src/main/java/com/ip/ddangddangddang/global/jwt/JwtUtil.java
Labels: enhancement, refactor

#53 Feat/front : 프론트 로그인 구현
  front/src/App.jsx
  front/src/layouts/auth.jsx
  front/src/pages/auth/index.js
  front/src/pages/auth/sign-in.jsx
  front/src/routes.jsx
  front/vite.config.js
Labels: bug, enhancement, refactor

#55 Feat/jwt : 개발용 임시 무제한 JWT 토큰
  src/main/java/com/ip/ddangddangddang/global/jwt/JwtUtil.java
Labels: refactor

#59 Feat/global : 비공개 경매에서 실시간 경매로 바꾸는 로직 구현 및 전체적인 코드컨벤션
  .gitignore
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/handler/AuctionEventHandler.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/domain/bid/dto/response/BidResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/bid/model/BidModel.java
  src/main/java/com/ip/ddangddangddang/domain/bid/repository/BidRepository.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/AuctionValidator.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
  src/main/java/com/ip/ddangddangddang/domain/comment/service/CommentService.java
  src/main/java/com/ip/ddangddangddang/domain/file/controller/FileController.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/request/FileCreateRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/response/FileCreateResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/dto/response/FileReadResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileService.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/S3Service.java
  src/main/java/com/ip/ddangddangddang/domain/result/entity/Result.java
  src/main/java/com/ip/ddangddangddang/domain/result/repository/ResultRepository.java
  src/main/java/com/ip/ddangddangddang/domain/result/service/ResultService.java
  src/main/java/com/ip/ddangddangddang/domain/town/entity/Town.java
  src/main/java/com/ip/ddangddangddang/domain/town/service/TownService.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/service/UserService.java
  src/main/java/com/ip/ddangddangddang/global/config/WebSecurityConfig.java
  src/main/java/com/ip/ddangddangddang/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ip/ddangddangddang/global/jwt/JwtUtil.java
  src/main/java/com/ip/ddangddangddang/global/redis/RedisKeyExpiredListener.java
  src/main/java/com/ip/ddangddangddang/global/security/CustomAuthentication.java
  src/main/java/com/ip/ddangddangddang/global/security/JwtAuthenticationFilter.java
  src/main/java/com/ip/ddangddangddang/global/security/JwtAuthorizationFilter.java
  src/main/java/com/ip/ddangddangddang/global/security/UserDetailsImpl.java
Labels: enhancement, refactor

#58 Doc/readme : readme update
  README.md
Labels: documentation

#65 Feat/bid : 입찰 가격 비교 기준 변경 및 분산락 finally 해제
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
  src/main/java/com/ip/ddangddangddang/global/aop/RedisLockAspect.java
Labels: bug, refactor

#66 Feat/bid : 불필요한 예외처리 삭제
  src/main/java/com/ip/ddangddangddang/global/aop/RedisLockAspect.java
Labels: refactor

#67 Feat/redis : 분산 락 사용 시 상위 트랜잭션이 있으면 안되는 에러코드 수정
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/request/AuctionRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/bid/dto/request/BidRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
Labels: enhancement

#68 Feat/auction : 캐싱시에 역직렬화 오류 해결
  build.gradle
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionListResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/AuctionResponseDto.java
  src/main/java/com/ip/ddangddangddang/domain/auction/dto/response/CustomSlice.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: bug

#70 Feat/auction : Slice 캐싱 불가 이슈로 인한 List 반환타입 변경
  src/main/java/com/ip/ddangddangddang/domain/auction/controller/AuctionController.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepository.java
  src/main/java/com/ip/ddangddangddang/domain/auction/repository/AuctionQueryRepositoryImpl.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: refactor

#71 Feat/bid : SSE + Redis pub/sub 적용
  src/main/java/com/ip/ddangddangddang/domain/bid/controller/BidController.java
  src/main/java/com/ip/ddangddangddang/domain/bid/dto/event/BidEvent.java
  src/main/java/com/ip/ddangddangddang/domain/bid/dto/request/BidRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidEventPublisher.java
  src/main/java/com/ip/ddangddangddang/domain/bid/service/BidService.java
Labels: enhancement, refactor

#72 Feat/front : 메인화면 반환타입 Slice -> List로 변경
  front/src/pages/dashboard/Home.jsx
Labels: refactor

#73 Feat/auction : Cache 어노테이션 Key 제거
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: refactor

#74 Feat/front : 메인화면 무한스크롤 반복 출력 해결
  front/src/pages/dashboard/Home.jsx
Labels: bug

#75 Feat/town : townlist 엑셀파일 변경버전 추가
  src/main/resources/townlist.xlsx
Labels: documentation

#78 Feat/front : 경매 게시물 올리는 기능 구현
  front/index.html
  front/src/api/file.js
  front/src/pages/auth/SignUp.jsx
  front/src/pages/dashboard/CreateAuction.jsx
  front/src/pages/dashboard/Home.jsx
  front/src/routes.jsx
  src/main/resources/static/assets/index-bc7c805e.js
  src/main/resources/static/index.html
Labels: enhancement

#80 Feat/auction : 내용 수정 시 캐시 비우기 구현
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: refactor

#81 Feat/mail : 경매 종료 시 판매자와 낙찰자에게 메일보내기
  build.gradle
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/global/mail/MailService.java
  src/main/resources/static/assets/index-65c53f27.js
  src/main/resources/static/assets/index-d8e93889.js
  src/main/resources/static/index.html
Labels: enhancement, refactor

#82 Feat/mail : SES 제거
  src/main/java/com/ip/ddangddangddang/global/config/AwsConfig.java
Labels: refactor

#84 Feat/global : 리드미에 아키텍처 추가
  README.md
Labels: documentation

#86 Test/user : userServiceTest 코드 구현
  src/main/java/com/ip/ddangddangddang/domain/town/service/TownService.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserLocationRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserSignupRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/service/UserService.java
  src/test/java/com/ip/ddangddangddang/common/TownFixture.java
  src/test/java/com/ip/ddangddangddang/common/UserFixture.java
  src/test/java/com/ip/ddangddangddang/domain/user/service/UserServiceTest.java
Labels: refactor, test

#87 Test/bid : BidServiceTest 작성
  src/main/java/com/ip/ddangddangddang/domain/bid/entity/Bid.java
  src/test/java/com/ip/ddangddangddang/domain/bid/service/BidServiceTest.java
  src/test/java/com/ip/ddangddangddang/domain/bid/values/BidServiceTestValues.java
Labels: test

#88 Test/comment : CommentServiceTest 작성
  src/main/java/com/ip/ddangddangddang/domain/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/comment/entity/Comment.java
  src/test/java/com/ip/ddangddangddang/domain/comment/service/CommentServiceTest.java
  src/test/java/com/ip/ddangddangddang/domain/comment/values/CommentServiceTestValues.java
Labels: test

#89 Test/user : UserControllerTest 구현
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserLocationRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserSigninRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserSignupRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/com/ip/ddangddangddang/domain/user/dto/response/UserResponse.java
  src/test/java/com/ip/ddangddangddang/common/ControllerTest.java
  src/test/java/com/ip/ddangddangddang/common/UserFixture.java
  src/test/java/com/ip/ddangddangddang/domain/user/controller/UserControllerTest.java
  src/test/java/com/ip/ddangddangddang/domain/user/dto/UserSigninRequestDtoTest.java
  src/test/java/com/ip/ddangddangddang/domain/user/entity/UserTest.java
Labels: refactor, test

#90 Test/bid : BidEventPublisherTest 작성
  src/test/java/com/ip/ddangddangddang/domain/bid/service/BidEventPublisherTest.java
  src/test/java/com/ip/ddangddangddang/domain/bid/values/BidServiceTestValues.java
Labels: test

#92 Feat/auction : Auction Controller 테스트 코드 추가
  src/test/java/com/ip/ddangddangddang/domain/auction/controller/AuctionControllerTest.java
  src/test/java/com/ip/ddangddangddang/domain/auction/values/AuctionServiceTestValues.java
Labels: test

#93 Test/bid : BidControllerTest 작성
  src/test/java/com/ip/ddangddangddang/domain/bid/controller/BidControllerTest.java
  src/test/java/com/ip/ddangddangddang/domain/bid/service/BidEventPublisherTest.java
  src/test/java/com/ip/ddangddangddang/domain/bid/service/BidServiceTest.java
  src/test/java/com/ip/ddangddangddang/domain/bid/values/BidTestValues.java
Labels: test

#95 Feat/auction : 코드리뷰 반영 코드 리팩터링
  src/main/java/com/ip/ddangddangddang/domain/auction/event/AuctionKeyExpiredEvent.java
  src/main/java/com/ip/ddangddangddang/domain/auction/handler/AuctionEventHandler.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/domain/file/service/FileService.java
  src/main/java/com/ip/ddangddangddang/global/common/controller/MainController.java
  src/main/java/com/ip/ddangddangddang/global/config/DynamicRoutingDataSource.java
  src/main/java/com/ip/ddangddangddang/global/redis/RedisKeyExpiredListener.java
  src/main/java/com/ip/ddangddangddang/global/s3/FileUploadService.java
  src/main/java/com/ip/ddangddangddang/global/s3/S3Service.java
  src/test/java/com/ip/ddangddangddang/domain/file/service/FileServiceTest.java
  src/test/java/com/ip/ddangddangddang/domain/file/service/S3ServiceTest.java
Labels: refactor

#96 Test/mail : mailServiceTest 구현
  src/main/java/com/ip/ddangddangddang/global/mail/MailService.java
  src/test/java/com/ip/ddangddangddang/common/AuctionFixture.java
  src/test/java/com/ip/ddangddangddang/common/FileFixture.java
  src/test/java/com/ip/ddangddangddang/domain/mail/MailServiceTest.java
Labels: refactor, test

#111 Feat/auction : Cache Evict 적용
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
Labels: refactor

#112 Dev : 유저 테스트용 배포
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/auction/service/AuctionService.java
  src/main/java/com/ip/ddangddangddang/global/jwt/JwtUtil.java
  src/main/java/com/ip/ddangddangddang/global/redis/RedisService.java
  src/main/java/com/ip/ddangddangddang/global/security/JwtAuthorizationFilter.java
Labels: enhancement

#113 Feat/global : 시간이 이상하게 나오던 오류 해결
  src/main/java/com/ip/ddangddangddang/domain/auction/entity/Auction.java
  src/main/java/com/ip/ddangddangddang/domain/common/timestamp/Timestamp.java
  src/main/java/com/ip/ddangddangddang/domain/user/entity/User.java
Labels: bug

#117 Feat/global : Redis Keyspace Notification 해결
  .github/workflows/test.yml
  src/main/java/com/ip/ddangddangddang/global/redis/RedisKeyExpiredListener.java
Labels: bug

#120 Feat/test : 분산락 테스트코드 작성
  build.gradle
  src/test/java/com/ip/ddangddangddang/global/lock/DistributedLockTest.java
Labels: test

#127 feat/global : Update README.md
  README.md
Labels: documentation
